
model:
    checkpoint: ./ckpt/pretrained-AgainstOTE.pt

sample:
  seed: 2020
  num_samples: 1000
  beam_size: 1000
  max_steps: 30
  threshold:
    focal_threshold: 0.5
    pos_threshold: 0.0625
    element_threshold: 0.075
    hasatom_threshold: 0.15
    bond_threshold: 0.1
